version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orders_db

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  redis:
    image: 'redis'
    ports:
      - "6379:6379"

#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    environment:
#      - POSTGRES_NAME=orders_db
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_HOST=db
#      - POSTGRES_PORT=5432
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#    depends_on:
#      - db
#      - redis